---
title: "Shiny App Self Review"
bibliography: myref.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

I have done the previous assignment about shiny app and I think that self review is an important part of the learning process.So now I will review my app and provide some points of improvement,which may help me to do better in the future.

### About My Shiny App

This is an shiny app about Australia coronavirus.It helps people to know the coronavirus data of daily cases and cumulative cases of different types in different states of Australia between 2020-01-12 to 2020-10-02.

[This is the link of my shiny app.](https://yiwen-liu.shinyapps.io/app_about_coronavirus/)From the website,people can change their inputs and get some specific coronavirus data they want from the interactive plots and table.

For example,if people select one state in the list,they would get an interactive plot about the daily cases of different types in the related state.The date of the plot is between the date range they choose at first.If they click a point on the plot,they will get the text about the type,date and number of cases this point represents. 

### Self Review

**1. What did you do well?**    

- I think the interaction between the different kinds of inputs and their outputs,two plots and a table,is completed well,especially for me who is exposed to shiny for the first time.

- Besides,I found a good dataset in which it contains the coronavirus data grouping by different states in one country.Before this,I just found some datasets grouping by countries in the world.It really helps me to clearly show the data according to different states of Australia in this shiny app,which could help people to get some more detailed information.

**2. What are the points you can improve on?**

- I think the layout of this shiny app is not very beautiful,which cannot effectively appeal people's attention.Maybe it can be improved from the following aspects:

  - First,the content of the about section will be displayed more clearly if there is a textbox which can contain the content in it.Now its content is not separated with the paragraph below using an obvious sign.It just uses a blank row,so sometimes it may make people confused. 

  - Second,it would be more beautiful if the plot and table about the cumulative cases of different types in different states of Australia are put in the same row.People could see and compare them more conveniently.

**3. What are some things that you’d like to add that’s plausible?**

- To the table,it just shows the cumulative cases of different types in different states in the last day you choose in the date range and it not shows the sum of these cases in a country granularity.It is great and plausible to add a new row on the bottom of table to show it,which makes people understand the data more intuitively.

**4. What are some things that you’d like to add that cannot be done yet due to limitation in data or technology?**

- To the table,I want to add a row which represents the sum of the cumulative cases in a country granularity but it does not work because the interaction is wrong.

- To the plot and table about the cumulative cases of different types in different states of Australia,I also try to put them in one row,but it does not succeed because of my limited skills.I only can put two paragraphs of text in one row but it does not work when I change text to plots.


*  *  *  *